declare class Key
	function __eq (self, rhs: Key): boolean
end

declare Input: {
	--- Returns true if this key is currently held down.
	getKey: (key: Key) -> boolean,
	--- Returns true if this key was pressed this frame.
	getKeyDown: (key: Key) -> boolean,
	--- Returns true if this key was released this frame.
	getKeyUp: (key: Key) -> boolean,
	--- Returns the value of the analog input for the given axis.
	getAnalog: (key: Key) -> number,
	--- Returns the position delta of the mouse since the last frame.
	getMouseDelta: () -> Vec2,
	--- https://docs.unrealengine.com/5.1/en-US/API/Runtime/InputCore/EKeys/
	Key: {
		AnyKey: Key,
		Tab: Key,
		Enter: Key,
		Pause: Key,
		CapsLock: Key,
		Escape: Key,
		SpaceBar: Key,
		PageUp: Key,
		PageDown: Key,
		End: Key,
		Home: Key,
		Left: Key,
		Up: Key,
		Right: Key,
		Down: Key,
		Insert: Key,
		BackSpace: Key,
		Delete: Key,
		Zero: Key,
		One: Key,
		Two: Key,
		Three: Key,
		Four: Key,
		Five: Key,
		Six: Key,
		Seven: Key,
		Eight: Key,
		Nine: Key,
		A: Key,
		B: Key,
		C: Key,
		D: Key,
		E: Key,
		F: Key,
		G: Key,
		H: Key,
		I: Key,
		J: Key,
		K: Key,
		L: Key,
		M: Key,
		N: Key,
		O: Key,
		P: Key,
		Q: Key,
		R: Key,
		S: Key,
		T: Key,
		U: Key,
		V: Key,
		W: Key,
		X: Key,
		Y: Key,
		Z: Key,
		NumPadZero: Key,
		NumPadOne: Key,
		NumPadTwo: Key,
		NumPadThree: Key,
		NumPadFour: Key,
		NumPadFive: Key,
		NumPadSix: Key,
		NumPadSeven: Key,
		NumPadEight: Key,
		NumPadNine: Key,
		Multiply: Key,
		Add: Key,
		Subtract: Key,
		Decimal: Key,
		Divide: Key,
		F1: Key,
		F2: Key,
		F3: Key,
		F4: Key,
		F5: Key,
		F6: Key,
		F7: Key,
		F8: Key,
		F9: Key,
		F10: Key,
		F11: Key,
		F12: Key,
		NumLock: Key,
		ScrollLock: Key,
		LeftShift: Key,
		RightShift: Key,
		LeftControl: Key,
		RightControl: Key,
		LeftAlt: Key,
		RightAlt: Key,
		LeftCommand: Key,
		RightCommand: Key,
		Semicolon: Key,
		Equals: Key,
		Comma: Key,
		Hyphen: Key,
		Underscore: Key,
		Period: Key,
		Slash: Key,
		Tilde: Key,
		LeftBracket: Key,
		Backslash: Key,
		RightBracket: Key,
		Apostrophe: Key,
		Quote: Key,
		LeftParantheses: Key,
		RightParantheses: Key,
		Ampersand: Key,
		Asterix: Key,
		Caret: Key,
		Dollar: Key,
		Exclamation: Key,
		Colon: Key,
		A_AccentGrave: Key,
		E_AccentGrave: Key,
		E_AccentAigu: Key,
		C_Cedille: Key,
		Section: Key,

		-- Mouse
		MouseX: Key,
		MouseY: Key,
		Mouse2D: Key,
		MouseScrollUp: Key,
		MouseScrollDown: Key,
		MouseWheelAxis: Key,
		LeftMouseButton: Key,
		RightMouseButton: Key,
		MiddleMouseButton: Key,
		ThumbMouseButton: Key,
		ThumbMouseButton2: Key,
	},
	Gamepad: {
		LeftX: Key,
		LeftY: Key,
		Left2D: Key,
		RightX: Key,
		RightY: Key,
		Right2D: Key,
		DPad_Up: Key,
		DPad_Down: Key,
		DPad_Right: Key,
		DPad_Left: Key,
		LeftStick_Up: Key,
		LeftStick_Down: Key,
		LeftStick_Right: Key,
		LeftStick_Left: Key,
		RightStick_Up: Key,
		RightStick_Down: Key,
		RightStick_Right: Key,
		RightStick_Left: Key,
		Special_Left: Key,
		Special_Right: Key,
		FaceButton_Bottom: Key,
		FaceButton_Right: Key,
		FaceButton_Left: Key,
		FaceButton_Top: Key,
		LeftTriggerAxis: Key,
		RightTriggerAxis: Key,
		LeftShoulder: Key,
		RightShoulder: Key,
		LeftTrigger: Key,
		RightTrigger: Key,
		LeftThumbstick: Key,
		RightThumbstick: Key,
		OculusTouch_Left_Thumbstick: Key,
		OculusTouch_Left_FaceButton1: Key,
		OculusTouch_Left_Trigger: Key,
		OculusTouch_Left_FaceButton2: Key,
		OculusTouch_Right_Thumbstick: Key,
		OculusTouch_Right_FaceButton1: Key,
		OculusTouch_Right_Trigger: Key,
		OculusTouch_Right_FaceButton2: Key,
	}
}
